# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - walka-go

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        buildkitd-flags: --debug

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_cb1ad1cd1ea5412b96c5d3032493bd41 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_1332daa5cd0b4291a17fa8ef37022b6d }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_cb1ad1cd1ea5412b96c5d3032493bd41 }}/clooux/obiekt-go:${{ github.sha }}
        file: ./Week5/backend/Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'walka-go'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_ad95985068c14725a858c768edaeba62 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_cb1ad1cd1ea5412b96c5d3032493bd41 }}/clooux/obiekt-go:${{ github.sha }}'
